### ISSUE TITLE
reference img in CSS

### ISSUE THREAD

**Issue by infacq** [thereactivestack/kickstart-meteor-react-router#71]
how do reference img in css

**Comment by eXon** [comment]
you just use a relative path. It can be anywhere. Example:

```css
.example {
  background: url('img/background.png');
}
```

Webpack will automatically bundle your image for you :) It means you can have your images in the same folder than your CSS file.
